#pragma once
#include "targetver.h"
#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS
#include <afxwin.h>
#include <afxext.h>
#include <afxdisp.h>
#include <afxdialogex.h>
#include <afxcontrolbars.h>
#include <afxcmn.h>
#include <gdiplus.h>
#undef min
#undef max
